<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Required meta tags -->

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="../assets/bootstrap.min.css">
    <link rel="stylesheet" href="../assets/owl.carousel.min.css">
    <link rel="stylesheet" href="../assets/owl.theme.default.min.css">

    <!-- Tops CSS -->
    <link rel="stylesheet" href="../assets/homeandliving2019/style.css">

    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="../assets/popper.min.js"></script>
    <script src="../assets/bootstrap.min.js"></script>
    <script src="../assets/owl.carousel.min.js"></script>
    <script src="../assets/homeandliving2019/JsBarcode.all.min.js"></script>
  
    <title>Tops Online</title>

    <!-- Recommended favicon format -->
    <link rel="icon" type="image/png" href="https://www.tops.co.th/../assets/icons/favicon.png">
    <!-- Apple Touch Icon -->
    <link rel="apple-touch-icon" href="https://www.tops.co.th/../assets/icons/apple-icon.png">
    <!-- To run web application in full- screen -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <!-- Global site tag (gtag.js) - Google Analytics --> <script async src="https://www.googletagmanager.com/gtag/js?id=UA-104800123-8"></script>
    
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'UA-104800123-8');
    </script>
</head>
<body>
    <div class="app">
        <div class="tops-welcome">
            <div class="container">
                <div class="welcome-text">
                    <h2 id="welcome-title" class="title"><strong>สวัสดี!</strong> คุณลูกค้าคนพิเศษ</h2>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="tops-highlight">
            <div class="container">
                <div class="tops-highlight-shadow" style="margin-bottom: 25px">
                    <img src="../assets/homeandliving2019/img/gardending.png">
                </div>
<!--                 <div class="tops-highlight-shadow">
                    <a href="https://www.tops.co.th/th/mom-and-kids?utm_source=sms_the1&utm_medium=sms&utm_campaign=|da:20190327|ch:sms|br:topsonline|cat:topsonline|cm:the1-babyandkids|">  
                        <img src="../assets/img/second-banner.png">
                    </a>
                </div> -->
            </div>
        </div>

<div id="cpn9-content" class="tops-card">
    <div class="container">
        <h2 class="title"><a id="itemcoupon-title" href="#"><span style="color:#EBE728;font-size:20px;">คูปองส่วนลดพิเศษเฉพาะคุณ</span> <span style="color:red; font-size: 40px;text-shadow: 2px 2px #000;margin-right: 15px;margin-left:13px">ฟรี!</span></a></h2>
        <div class="promo">
            <div id="owl-cpn9" class="owl-carousel owl-theme owl-stage-show owl-loaded owl-drag">
                <div class="owl-stage-outer">
                    <div class="owl-stage" style="transform: translate3d(0px, 0px, 0px); transition: all 0s ease 0s; width: 2340px;">
                        <div class="owl-item active" style="width: 570px; margin-right: 15px;">
                            <div class="item">
                                <a class="bar-display" data-customer="450302" data-barcode="2331420190330" data-type="CPN9" href="#"><img src="https://crm.tops.co.th/assets/homeandliving2019/coupon/2331420190330.png"></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="owl-nav disabled">
                    <button type="button" role="presentation" class="owl-prev"><span aria-label="Previous">‹</span></button>
                    <button type="button" role="presentation" class="owl-next"><span aria-label="Next">›</span></button>
                </div>
            </div>
            <div class="more-condition">
                <a href="#">
                    <img src="https://crm.tops.co.th/accummar2019/assets/img/icon-condition.svg" alt="more">
                    <h3 class="condition-title">เงื่อนไขคูปอง</h3>
                </a>
                <div class="condition-detail">
                    <div class="modal-th">
                        <p class="-top"><strong>เงื่อนไขการใช้คูปอง</strong></p>
                        <ul>
                            <li>คูปองส่วนลดนี้ใช้เป็นส่วนลดเมื่อซื้อสินค้าตามที่กำหนด</li>
                            <li>คูปองส่วนลดนี้สามารถใช้ร่วมกับคูปองส่วนลดอื่นได้ หากยอดซื้อของใบเสร็จนั้น <u>มากกว่าหรือเท่ากับ</u>ยอดซื้อตามเงื่อนไขของแต่ละคูปองรวมกัน</li>
                            <li>คูปองนี้ใช้เป็นส่วนลดเมื่อซื้อสินค้า <strong>ที่เซ็นทรัล ฟู้ด ฮอลล์ และท็อปส์ ทุกสาขา</strong></li>
                            <li>คูปองนี้ใช้เป็นส่วนลดสำหรับสมาชิกเดอะวัน</li>
                            <li>คูปองนี้ไม่สามารถลดเพิ่มจากสินค้าที่ลดราคาอยู่แล้ว</li>
                            <li>คูปองนี้ไม่สามารถแลกแลกเปลี่ยนหรือทอนเป็นเงินสดได้</li>
                            <li>ขอสงวนสิทธิ์การใช้คูปองที่บันทึกผ่านการจับภาพหน้าจอทุกกรณี</li>
                            <li>บริษัท เซ็นทรัล ฟู้ด รีเทล จำกัด ขอสงวนสิทธิ์ในการเปลี่ยนแปลงเงื่อนไขโดยไม่ต้องแจ้งให้ทราบล่วงหน้า</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
        <div class="container">
            <div class="tops-highlight-shadow" style="margin-bottom: 25px">
                 <a  href="https://www.tops.co.th/th/home-2019?utm_source=sms_the1&utm_medium=sms&utm_campaign=|da:20190404|ch:sms|br:topsonline|cat:topsonline|cm:the1-home|"><img src="https://crm.tops.co.th/assets/homeandliving2019/coupon/Gardending_online_CDS.png"></a>
            </div>
            <div class="more-condition">
                <a href="#">
                    <img src="https://crm.tops.co.th/accummar2019/assets/img/icon-condition.svg" alt="more">
                    <h3 class="condition-title">เงื่อนไขคูปอง</h3>
                </a>
                    <div class="condition-detail">
                        <div class="modal-th">
                            <p class="-top"><strong>เงื่อนไขคูปอง Tops online</strong></p>
                            <ul>
                                <li>สิทธิพิเศษเฉพาะสมาชิกเดอะวัน</li>
                                <li>โปรโมชั่นนี้สำหรับการสั่งซื้อผ่านท็อปส์ ออนไลน์เว็บไซต์และแอพพลิเคชัน เฉพาะจัดส่งภายในวันที่ 4 เมษายน  - 21 เมษายน 2562 เท่านั้น</li>
                                <li>ยกเว้นสินค้าซื้อเหมา (การซื้อสินค้าที่มีบาร์โค้ดเดียวกันตั้งแต่ 7 ชิ้นขึ้นไปต่อใบเสร็จ) สินค้ายกแพคยี่ห้อเอ็ม 150 และยี่ห้อเบอร์ดี้, กระเช้าของขวัญทุกชนิด, เครื่องดื่มผสมแอลกอฮอลล์, อาหารเสริมและนมผงสำหรับเด็กทารกและสูตรต่อเนื่อง, น้ำมันประกอบอาหาร และน้ำตาลประกอบอาหาร, ยา, สินค้าทางการแพทย์ และเวชสำอาง</li>
                                <li>ลูกค้าจะได้รับส่วนลด เมื่อซื้อสินค้าครบตามเงื่อนไขที่กำหนด</li>
                                <li>จำกัดการรับส่วนลดมูลค่า 100 บาท 1 สิทธิ์ ต่อหมายเลขเดอะวัน ตลอดรายการ</li>
                                <li>คูปองส่วนลดนี้ สามารถใช้ร่วมกับคูปองส่วนลดอื่นได้ หากยอดซื้อของใบเสร็จนั้นมากกว่าหรือเท่ากับยอดซื้อที่ระบุในเงื่อนไขของแต่ละคูปองรวมกัน</li>
                                <li>ส่วนลดไม่สามารถแลกเปลี่ยนหรือทอนเป็นเงินสดได้</li>
                                <li>บริษัท เซ็นทรัล ฟู้ด รีเทล จำกัด ขอสงวนสิทธิ์ในการเปลี่ยนแปลงเงื่อนไข โดยไม่ต้องแจ้งให้ทราบล่วงหน้าหรือทอนเป็นเงินสดได้</li>
                            </ul>

                        </div>
                    </div>
                </div>
                    </div>

        <div class="tops-card">
            <div class="container">
                <h2 class="title -credits">
                  <a id="credits-title">โปรโมชั่นบัตรเครดิต</a></br>
                  <span id="credits-subtitle">เมื่อช็อปที่ Cental Food Hall &amp; Tops</span>
              </h2>
                <div class="promo">
                    <div id="owl-credits" class="owl-carousel owl-theme owl-stage-show owl-loaded owl-drag">
                        <div class="owl-stage-outer">
                            <div class="owl-stage" style="transform: translate3d(0px, 0px, 0px); transition: all 0s ease 0s; width: 2340px;">
                                <div class="owl-item active" style="width: 570px; margin-right: 15px;">
                                    <div class="item">
                                        <a href="http://bit.ly/2CvcidS"><img src="../assets/central-en.jpg"></a>
                                    </div>
                                </div>
                                <div class="owl-item" style="width: 570px; margin-right: 15px;">
                                    <div class="item">
                                        <a href="http://bit.ly/2TNMBim"><img src="../assets/uob-en.jpg"></a>
                                    </div>
                                </div>
                                <div class="owl-item" style="width: 570px; margin-right: 15px;">
                                    <div class="item">
                                        <a href="http://bit.ly/2HftnN2"><img src="../assets/ktc-en.jpg"></a>
                                    </div>
                                </div>
                                <div class="owl-item" style="width: 570px; margin-right: 15px;">
                                    <div class="item">
                                        <a href="http://bit.ly/2CfjcDK"><img src="../assets/krungsri-en.jpg"></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <footer class="tops-footer">
            <div class="container">
                <img width="200" height="39" src="../assets/tops-footer.png" alt="Tops">
            </div>
        </footer>

    <!-- Modal -->
    <div class="modal fade" id="conditionModal" tabindex="-1" role="dialog" aria-labelledby="conditionModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div id="modal-body" class="modal-body">
            <div class="condition-moda-th">
              <p>การใช้คูปองที่หน้าร้าน / สาขา</p>
              <ul>
                <li>คูปองไม่สามารถนำกลับมาใช้ต่อได้ เมื่อเวลาที่แสดงหมดลง</li>
                <li>เมื่อท่านกดใช้ต้องแสดงบาร์โค้ดต่อแคชเชียร์ในระยะเวลาที่กำหนด</li>
                <li>หากปิดหน้าแสดงคูปองท่านจะไม่สามารถกลับมาใช้คูปองได้</li>
              </ul>
              <p class="font-weight-bold">ท่านต้องการดำเนินการต่อหรือไม่?</p>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary btn-cancel" data-dismiss="modal">ยกเลิก</button>
            <button type="button" class="btn btn-primary btn-confirm">ตกลง</button>
          </div>
        </div>
      </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="barcodeModal" tabindex="-1" role="dialog" aria-labelledby="barcodeModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div id="modal-body" class="modal-body">
            <div class="coupon-timer text-center">
              <div class="text-right btn-close">
                <span data-dismiss="modal">x</span>
              </div>
              <h4 class="font-weight-bold title-timer">...</h4>
              <h2 class="text-danger display-4 mt-2 title-countdown" id="timer">10:00</h2>
              <h6 class="text-danger px-4 font-weight-bold mt-3 title-caution">...</h6>
              <h5 class="mt-5 px-4 title-show">...</h5>
            </div>
            <div class="coupon-barcode text-center mt-5">
              <div class="barcode-container">
                <div id="barcode-type" class="text-right">...</div>
                <div id="barcode-image" class="barcode-image"></div>
<!--                 <span id="barcode-number">XXXXXXXXXXX</span>  
 -->              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>


    <script>

        $('.condition-title').html("เงื่อนไขการใช้คูปอง");
        $('.condition-moda-th').removeClass('d-none');
        $('.btn-cancel').html('ยกเลิก');
        $('.btn-confirm').html('ตกลง');
        $('.title-timer').html('ระยะเวลาการใช้งาน');
        $('.title-caution').html('หากท่านปิดหน้านี้คูปองจะไม่สามารถใช้ได้อีก');
        $('.title-show').html('กรุณาแสดงเลขบาร์โค้ดต่อแคชเชียร์');

        var carousel_credits = $('#owl-credits');
        var carousel_cpn9 = $('#owl-cpn9');

        var userIP;
        $.getJSON('https://ipapi.co/json/',
            function(data){
                userIP = data.ip;
                var readCookie = Cookies.get('homeandliving2019-gardending');
                if(readCookie != null){
                    if(userIP == readCookie){
                    $(".bar-display").append("<div class='stamp'><img src='https://crm.tops.co.th/focusstore02/assets/img/icon-used.svg' alt='stamp' /></div>").addClass("coupon-used");
                    }
                }        
            });

        carousel_credits.owlCarousel({
            items: 1,
            lazyLoad: true,
            dots: true,
            margin: 15,
        });

        carousel_cpn9.owlCarousel({
              items: 1,
              lazyLoad: true,
              //loop: true,
              dots: true,
              margin: 0,
              //autoplay: true,
              //autoplayTimeout: 3000,
              //autoplayHoverPause: true
        });


          $( ".bar-display" ).click(function(e) {
            e.preventDefault();

            var data_customer = $( this ).attr("data-customer");
            var data_barcode = $( this ).attr("data-barcode");
            var data_type = $( this ).attr("data-type");

            if(data_type == 'CPN8') {
              data_type = 'CPN2';
            }

            $('.btn-confirm').attr('data-customer', data_customer)
            $('.btn-confirm').attr('data-barcode', data_barcode)
            $('.btn-confirm').attr('data-type', data_type)

            $('#conditionModal').modal('show');
          
          });

            $( ".more-condition" ).click(function(e) {
              e.preventDefault();
              $( this ).toggleClass( "-shadow" );
              //$( this ).toggleClass( "-show-condition" );
              $( this ).find(".condition-detail").toggleClass( "-show-condition" );
              //$( this ).find(".condition-detail").slideToggle( "slow", function() {
                
              //});
            });

            var setFirstTimer = null;

            $( ".btn-confirm" ).click(function(e) {
                $('#conditionModal').modal('hide');

                Cookies.set("homeandliving2019-gardending", userIP, {
                   expires : 60,           
                   path    : '/',
                   domain  : 'crm.tops.co.th', 
                   secure  : true 
                });

                $(".bar-display").append("<div class='stamp'><img src='https://crm.tops.co.th/focusstore02/assets/img/icon-used.svg' alt='stamp' /></div>").addClass("coupon-used");

                $( '#barcode-type' ).html( "CPN2" );
                $( '#barcode-image' ).html( '<svg class="barcode" jsbarcode-format="CODE128" jsbarcode-value="2331420190330" jsbarcode-width="2" jsbarcode-height="50" jsbarcode-textmargin="0"></svg>' );
                    JsBarcode(".barcode").init();

                // $( '#barcode-number' ).html( "data_barcode" );
                $( '#timer' ).html( '10:00' );

                $('#barcodeModal').modal('show');

                if(setFirstTimer == null) {
                  startTimer();
                  setFirstTimer = "SET";
                }
            });

            function startTimer() {
              var presentTime = document.getElementById('timer').innerHTML;
              var timeArray = presentTime.split(/[:]+/);
              var m = timeArray[0];
              var s = checkSecond((timeArray[1] - 1));
              if(s==59){m=m-1}
              //if(m<0){alert('timer completed')}
              
              document.getElementById('timer').innerHTML = m + ":" + s;
              if((m == 0) && (s == 0)) {
                $('#barcodeModal').modal('hide');
              }
              setTimeout(startTimer, 1000);
            }

            function checkSecond(sec) {
              if (sec < 10 && sec >= 0) {sec = "0" + sec}; // add zero in front of numbers < 10
              if (sec < 0) {sec = "59"};
              return sec;
            }


    </script>

</body>
</html>