<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Required meta tags -->

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="../assets/bootstrap.min.css">
    <link rel="stylesheet" href="../assets/owl.carousel.min.css">
    <link rel="stylesheet" href="../assets/owl.theme.default.min.css">

    <!-- Tops CSS -->
    <link rel="stylesheet" href="../assets/style.css">

    <script src="../assets/jquery-3.3.1.slim.min.js"></script>
    <script src="../assets/popper.min.js"></script>
    <script src="../assets/bootstrap.min.js"></script>
    <script src="../assets/owl.carousel.min.js"></script>

    <title>Tops Online</title>

    <!-- Recommended favicon format -->
    <link rel="icon" type="image/png" href="https://www.tops.co.th/../assets/icons/favicon.png">
    <!-- Apple Touch Icon -->
    <link rel="apple-touch-icon" href="https://www.tops.co.th/../assets/icons/apple-icon.png">
    <!-- To run web application in full- screen -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <!-- Global site tag (gtag.js) - Google Analytics --> <script async src="https://www.googletagmanager.com/gtag/js?id=UA-104800123-8"></script>
    
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'UA-104800123-8');
    </script>
</head>

<body>
    <div class="app">
        <div class="tops-welcome">
            <div class="container">
                <div class="welcome-text">
                    <h2 id="welcome-title" class="title"><strong>สวัสดี!</strong> คุณลูกค้าคนพิเศษ</h2>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="tops-highlight">
            <div class="container">
                <div class="tops-highlight-shadow" style="margin-bottom: 25px">
                    <img src="../assets/img/banner-infant.png">
                </div>
                <div class="tops-highlight-shadow">
                    <a href="https://www.tops.co.th/th/mom-and-kids?utm_source=sms_the1&utm_medium=sms&utm_campaign=|da:20190327|ch:sms|br:topsonline|cat:topsonline|cm:the1-babyandkids|">  
                        <img src="../assets/img/second-banner.png">
                    </a>
                </div>
            </div>
        </div>

        <div class="tops-card">
            <div class="container">
                <h2 class="title -credits">
                  <a id="credits-title">โปรโมชั่นบัตรเครดิต</a></br>
                  <span id="credits-subtitle">เมื่อช็อปที่ Cental Food Hall &amp; Tops</span>
              </h2>
                <div class="promo">
                    <div id="owl-credits" class="owl-carousel owl-theme owl-stage-show owl-loaded owl-drag">
                        <div class="owl-stage-outer">
                            <div class="owl-stage" style="transform: translate3d(0px, 0px, 0px); transition: all 0s ease 0s; width: 2340px;">
                                <div class="owl-item active" style="width: 570px; margin-right: 15px;">
                                    <div class="item">
                                        <a href="http://bit.ly/2CvcidS"><img src="../assets/central-en.jpg"></a>
                                    </div>
                                </div>
                                <div class="owl-item" style="width: 570px; margin-right: 15px;">
                                    <div class="item">
                                        <a href="http://bit.ly/2TNMBim"><img src="../assets/uob-en.jpg"></a>
                                    </div>
                                </div>
                                <div class="owl-item" style="width: 570px; margin-right: 15px;">
                                    <div class="item">
                                        <a href="http://bit.ly/2HftnN2"><img src="../assets/ktc-en.jpg"></a>
                                    </div>
                                </div>
                                <div class="owl-item" style="width: 570px; margin-right: 15px;">
                                    <div class="item">
                                        <a href="http://bit.ly/2CfjcDK"><img src="../assets/krungsri-en.jpg"></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <footer class="tops-footer">
            <div class="container">
                <img width="200" height="39" src="../assets/tops-footer.png" alt="Tops">
            </div>
        </footer>
    </div>

    <script>
        var carousel_credits = $('#owl-credits');

        carousel_credits.owlCarousel({
            items: 1,
            lazyLoad: true,
            dots: true,
            margin: 15,
        });
    </script>

</body>
</html>